### ISSUE TITLE
custom border style

### ISSUE THREAD

**Issue by assafb81** [markusenglund/react-switch#15]
Is it possible to add border style to the component?
I want to add style for the component with `react-swith-bg` class and to the component with `react-switch-handle` class.

Thanks

**Comment by markusenglund** [comment]
You can't use a border unfortunately, but you can use a box-shadow which can be made to look just like a border. [Here's an example](https://codesandbox.io/s/qvlmzqmxrj) (note the `styles.css` file). I added the following css:
```css
.react-switch-bg {
  box-shadow: 0px 0px 0px 5px #bada55;
}
.react-switch-handle {
  box-shadow: 0px 0px 0px 5px #abcdef !important;
}
```
I'd normally recommend using the `boxShadow` and `activeBoxShadow` props to adjust the box-shadow though.
